title: Test title
author: akhinchey
email: akhinchey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  test description description.

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
